databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    rootDir: CollabRate
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn main.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        value: postgresql://mysite:BZFL7JbY1H5GJ2yAXvZiqfFlG1u3lFtq@dpg-d0ej7jqdbo4c738ofn9g-a.oregon-postgres.render.com/mysite_0bqo
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: mysite-8sga.onrender.com
      - key: GOOGLE_CLIENT_ID
        value: 744862480191-eh0lqnmc77vq47dr64mpq5gakk4gh2uf.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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

      # ← And your SITE_ID (must match Django’s SITE_ID in settings.py):
      - key: SITE_ID
        value: "1"